# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a9739ae93e971f3b2eb87c013edd4571a27b7b15bc0956d3a149c92b51a02bea10a823bc102e33d3f9b3122d03afa5594e151bd76ee49474ff6429ab242ed0

test:
  secret_key_base: 4292ece11542fd5c5ba5fb39505634b02a706082f8578e3ca46ceaaf16226a9c4967aebb49d78dc3624c86115d5b6ee486e9001d22daf1acebafdd47a12a3f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
